# ================================
# 🚀 Luckia Chat - Docker Compose
# Production-ready stack for EasyPanel
# ================================

version: '3.8'

services:
  # 🤖 Ollama Service
  ollama:
    image: ollama/ollama:latest
    container_name: luckia-chat-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - luckia-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 🎨 Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: luckia-chat-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
      - ollama
    networks:
      - luckia-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  # 🔧 Backend Service  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: production
    container_name: luckia-chat-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - AREA_CONFIG_PATH=/app/backend/config/area_config.json
      - SESSION_SECRET=${SESSION_SECRET:-your-super-secret-key-change-in-production}
    volumes:
      - backend-data:/app/database
      - backend-logs:/app/logs
    networks:
      - luckia-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${DOMAIN:-localhost}`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3001"

  # 📊 Monitoring (Opcional - para EasyPanel)
  monitoring:
    image: prom/prometheus:latest
    container_name: luckia-chat-monitoring
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - luckia-network
    profiles:
      - monitoring

# 🌐 Networks
networks:
  luckia-network:
    driver: bridge
    name: luckia-chat-network

# 💾 Volumes
volumes:
  ollama-data:
    driver: local
    name: luckia-chat-ollama
  backend-data:
    driver: local
    name: luckia-chat-db
  backend-logs:
    driver: local 
    name: luckia-chat-logs
  prometheus-data:
    driver: local
    name: luckia-chat-metrics

# 🔍 Extension fields for EasyPanel
x-easypanel-info:
  name: "Luckia Chat IA"
  description: "Sistema de chat con IA usando Ollama - Listo para EasyPanel"
  version: "3.0.0"
  author: "Luckia IT Team"
  ports:
    - port: 80
      name: "Frontend"
      description: "Interfaz de usuario principal"
    - port: 3001  
      name: "Backend API"
      description: "API REST del backend"
  environment:
    - name: "OLLAMA_BASE_URL"
      description: "URL del servidor Ollama (ej: http://192.168.1.206:11434)"
      required: true
    - name: "DOMAIN"
      description: "Dominio principal (ej: chat.luckia.com)"
      required: false
    - name: "SESSION_SECRET"
      description: "Clave secreta para sesiones (cambiar en producción)"
      required: true
  volumes:
    - name: "backend-data"
      description: "Base de datos SQLite y archivos de sesión"
    - name: "backend-logs"  
      description: "Logs del sistema"